---
- name: install nodejs
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash - && sudo apt-get install -y nodejs
  state: present
  update_cache: yes

- name: Install Node.js and PM2
  become: true
  npm:
    name: pm2
    global: yes

- name: "add environment variables"
  become: true
  copy:
    src: frontend.env.sh
    dest: /etc/profile.d/
